name: surgical
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision 
  - torchaudio
  - cudatoolkit=10.2
  - pandas
  - ipykernel
  - pip
  - pytest
  - pip:
    - "--editable=git+https://github.com/DiffEqML/torchdyn.git@43d22ce5e12dc1a298ef8c11e64f015b05a60765#egg=torchdyn"
    - wandb
    - pytorch-lightning


    
