name: surgical
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - ipywidgets
  - altair 
  - vega_datasets
  - python=3.8
  - numpy
  - jupyter
  - jupyterlab
  - matplotlib
  - pydantic
  - pip
  - pytest
  - scikit-learn
  - pytorch
  - torchvision 
  - torchaudio
  - pip:    
    - pytorch-lightning
    - tqdm
    - "--editable=git+https://github.com/DiffEqML/torchdyn.git@43d22ce5e12dc1a298ef8c11e64f015b05a60765#egg=torchdyn"

    
